export const flights = [
  ['LH 150',	'Lufthansa'	, '(NUE) Nuremberg',	'9:05 PM',	'Landed'],
  ['TP 7790', 'TAP Portugal'	, '(NUE) Nuremberg',	'9:05 PM',	'Landed'],
  ['TG 7962', 'Thai Airways International'	, '(NUE) Nuremberg',	'9:05 PM',	'Landed'],
  ['SK 8556', 'SAS'	, '(NUE) Nuremberg',	'9:05 PM',	'Landed'],
  ['CA 6075', 'Air China'	, '(NUE) Nuremberg',	'9:05 PM',	'Landed'],
  ['LH 1352',	'Lufthansa'	, '(WAW) Warsaw',	'9:10 PM',	'En Route'],
  ['NH 5887', 'ANA'	, '(WAW) Warsaw',	'9:10 PM',	'En Route'],
  ['LO 5378', 'LOT - Polish Airlines'	, '(WAW) Warsaw',	'9:10 PM',	'En Route'],
  ['LG 1493', 'Luxair'	, '(WAW) Warsaw',	'9:10 PM',	'En Route'],
  ['A3 1474', 'Aegean Airlines'	, '(WAW) Warsaw',	'9:10 PM',	'En Route'],
  ['LH 8384',	'Lufthansa'	, '(NRT) Tokyo',	'9:10 PM',	'En Route'],
  ['LH 1402',	'Lufthansa'	, '(PRG) Prague',	'9:10 PM',	'Landed'],
  ['TP 7934', 'TAP Portugal'	, '(PRG) Prague',	'9:10 PM',	'Landed' ],
  ['LG 1487', 'Luxair'	, '(PRG) Prague',	'9:10 PM',	'Landed' ],
  ['LH 1138',	'Lufthansa'	, '(BCN) Barcelona',	'9:15 PM',	'En Route'],
  ['CA 6293', 'Air China'	, '(BCN) Barcelona',	'9:15 PM',	'En Route'],
  ['TG 7656', 'Thai Airways International'	, '(BCN) Barcelona',	'9:15 PM',	'En Route'],
  ['SK 3380', 'SAS'	, '(BCN) Barcelona',	'9:15 PM',	'En Route'],
  ['LH 122',	'Lufthansa'	, '(MUC) Munich',	'9:15 PM',	'Landed'],
  ['LH 202',	'Lufthansa'	, '(TXL) Berlin',	'9:15 PM',	'Landed'],
  ['TP 7706', 'TAP Portugal'	, '(TXL) Berlin',	'9:15 PM',	'Landed'],
  ['LH 1342',	'Lufthansa'	, '(BUD) Budapest',	'9:20 PM',	'En Route'],
  ['SN 7147', 'Brussels Airlines'	, '(BUD) Budapest',	'9:20 PM',	'En Route'],
  ['TP 7978', 'TAP Portugal'	, '(BUD) Budapest',	'9:20 PM',	'En Route'],
  ['SK 3560', 'SAS'	, '(BUD) Budapest',	'9:20 PM',	'En Route'],
  ['LH 318',	'Lufthansa'	, '(FLR) Florence',	'9:20 PM',	'En Route'],
  ['NH 6007', 'ANA'	, '(FLR) Florence',	'9:20 PM',	'En Route'],
  ['CA 6188', 'Air China'	, '(FLR) Florence',	'9:20 PM',	'En Route'],
  ['LH 1068',	'Lufthansa'	, '(NCE) Nice',	'9:20 PM',	'En Route'],
  ['LH 1230',	'Lufthansa'	, '(GVA) Geneva',	'9:20 PM',	'Landed'],
  ['TG 7664', 'Thai Airways International'	, '(GVA) Geneva',	'9:20 PM',	'Landed'],
  ['LX 3677', 'SWISS'	, '(GVA) Geneva',	'9:20 PM',	'Landed'],
  ['LH 360',	'Lufthansa'	, '(BRE) Bremen',	'9:20 PM',	'Landed'],
  ['TP 7740', 'TAP Portugal'	, '(BRE) Bremen',	'9:20 PM',	'Landed'],
  ['LG 1445', 'Luxair'	, '(BRE) Bremen',	'9:20 PM',	'Landed'],
  ['KM 2850', 'Air Malta'	, '(BRE) Bremen',	'9:20 PM',	'Landed'],
  ['CA 6203', 'Air China'	, '(BRE) Bremen',	'9:20 PM',	'Landed'],
  ['EN 8830',	'Air Dolomiti'	, '(VRN) Verona',	'9:20 PM',	'Landed'],
  ['LH 9510', 'Lufthansa'	, '(VRN) Verona',	'9:20 PM',	'Landed'],
  ['LH 216',	'Lufthansa'	, '(DRS) Dresden',	'9:20 PM',	'Landed'],
  ['TP 7828', 'TAP Portugal'	, '(DRS) Dresden',	'9:20 PM',	'Landed'],
  ['KM 2870', 'Air Malta'	, '(DRS) Dresden',	'9:20 PM',	'Landed'],
  ['CA 6043', 'Air China'	, '(DRS) Dresden',	'9:20 PM',	'Landed'],
  ['A3 1444', 'Aegean Airlines'	, '(DRS) Dresden',	'9:20 PM',	'Landed'],
  ['LH 854',	'Lufthansa'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['TP 7908', 'TAP Portugal'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['NH 6173', 'ANA'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['OS 7443', 'Austrian'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['UA 9579', 'United Airlines'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['SN 7107', 'Brussels Airlines'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['CA 6099', 'Air China'	, '(HEL) Helsinki',	'9:25 PM',	'En Route'],
  ['LH 1024',	'Lufthansa'	, '(BRU) Brussels',	'9:25 PM',	'Landed'],
  ['TG 7662', 'Thai Airways International'	, '(BRU) Brussels',	'9:25 PM',	'Landed'],
  ['SN 7014', 'Brussels Airlines'	, '(BRU) Brussels',	'9:25 PM',	'Landed'],
  ['CA 6129', 'Air China'	, '(BRU) Brussels',	'9:25 PM',	'Landed'],
  ['A3 1434', 'Aegean Airlines'	, '(BRU) Brussels',	'9:25 PM',	'Landed'],
  ['LH 892',	'Lufthansa'	, '(RIX) Riga',	'9:25 PM',	'En Route'],
  ['NH 6056', 'ANA'	, '(RIX) Riga',	'9:25 PM',	'En Route'],
  ['LH 808',	'Lufthansa'	, '(ARN) Stockholm',	'9:30 PM',	'En Route'],
  ['LG 1405', 'Luxair'	, '(ARN) Stockholm',	'9:30 PM',	'En Route'],
  ['AI 8504', 'Air India'	, '(ARN) Stockholm',	'9:30 PM',	'En Route'],
  ['SK 3610', 'SAS'	, '(ARN) Stockholm',	'9:30 PM',	'En Route'],
  ['NH 6189', 'ANA'	, '(ARN) Stockholm',	'9:30 PM',	'En Route'],
  ['A3 1400', 'Aegean Airlines'	, '(ARN) Stockholm',	'9:30 PM',	'En Route'],
  ['LH 304',	'Lufthansa'	, '(TRN) Turin',	'9:30 PM',	'Landed'],
  ['LG 1507', 'Luxair'	, '(TRN) Turin',	'9:30 PM',	'Landed'],
  ['CA 6197', 'Air China'	, '(TRN) Turin',	'9:30 PM',	'Landed'],
  ['AI 120',	'Air India'	, '(DEL) Delhi',	'9:30 PM',	'En Route'],
  ['TP 7028', 'TAP Portugal'	, '(DEL) Delhi',	'9:30 PM',	'En Route'],
  ['LH 7252', 'Lufthansa'	, '(DEL) Delhi',	'9:30 PM',	'En Route'],
  ['JP 9420', 'Adria Airways'	, '(DEL) Delhi',	'9:30 PM',	'En Route'],
  ['LH 948',	'Lufthansa'	, '(MAN) Manchester',	'9:30 PM',	'En Route'],
  ['OS 7375', 'Austrian'	, '(MAN) Manchester',	'9:30 PM',	'En Route'],
  ['NH 5865', 'ANA'	, '(MAN) Manchester',	'9:30 PM',	'En Route'],
  ['LH 332',	'Lufthansa'	, '(VCE) Venice',	'9:30 PM',	'En Route'],
  ['LG 1525', 'Luxair'	, '(VCE) Venice',	'9:30 PM',	'En Route'],
  ['CA 6095', 'Air China'	, '(VCE) Venice',	'9:30 PM',	'En Route'],
  ['LH 922',	'Lufthansa'	, '(LHR) London',	'9:30 PM',	'En Route'],
  ['OU 5488', 'Croatia Airlines'	, '(LHR) London',	'9:30 PM',	'En Route'],
  ['TP 7696', 'TAP Portugal'	, '(HAM) Hamburg',	'9:30 PM',	'Landed'],
  ['LH 1370',	'Lufthansa'	, '(KRK) Krakow',	'9:40 PM',	'En Route'],
  ['SN 7121', 'Brussels Airlines'	, '(KRK) Krakow',	'9:40 PM',	'En Route'],
  ['NH 5891', 'ANA'	, '(KRK) Krakow',	'9:40 PM',	'En Route'],
  ['LO 5506', 'LOT - Polish Airlines'	, '(KRK) Krakow',	'9:40 PM',	'En Route'],
  ['OS 258',	'Austrian'	, '(GRZ) Graz',	'9:40 PM',	'En Route'],
  ['LH 1582', 'Lufthansa'	, '(GRZ) Graz',	'9:40 PM',	'En Route'],
  ['LH 1378',	'Lufthansa'	, '(GDN) Gdansk',	'9:40 PM',	'En Route'],
  ['UA 9262', 'United Airlines'	, '(GDN) Gdansk',	'9:40 PM',	'En Route'],
  ['LO 5402', 'LOT - Polish Airlines'	, '(GDN) Gdansk',	'9:40 PM',	'En Route'],
  ['TP 7760', 'TAP Portugal'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['TG 7954', 'Thai Airways International'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['SQ 2080', 'Singapore Airlines'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['OU 5416', 'Croatia Airlines'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['JP 9784', 'Adria Airways'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['AI 8851', 'Air India'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['CA 6035', 'Air China'	, '(DUS) Dusseldorf',	'9:40 PM',	'Landed'],
  ['LH 864',	'Lufthansa'	, '(OSL) Oslo',	'9:40 PM',	'En Route'],
  ['AI 8534', 'Air India'	, '(OSL) Oslo',	'9:40 PM',	'En Route'],
  ['SK 3644', 'SAS'	, '(OSL) Oslo',	'9:40 PM',	'En Route'],
  ['NH 6185', 'ANA'	, '(OSL) Oslo',	'9:40 PM',	'En Route'],
  ['A3 1414', 'Aegean Airlines'	, '(OSL) Oslo',	'9:40 PM',	'En Route'],
  ['LH 398',	'Lufthansa'	, '(LUX) Luxembourg',	'9:40 PM',	'Landed'],
  ['LG 1908', 'Luxair'	, '(LUX) Luxembourg',	'9:40 PM',	'Landed'],
  ['LH 982',	'Lufthansa'	, '(DUB) Dublin',	'9:45 PM',	'En Route'],
  ['SQ 2158', 'Singapore Airlines'	, '(DUB) Dublin',	'9:45 PM',	'En Route'],
  ['OS 7471', 'Austrian'	, '(DUB) Dublin',	'9:45 PM',	'En Route'],
  ['NH 5456', 'ANA'	, '(DUB) Dublin',	'9:45 PM',	'En Route'],
  ['OS 288',	'Austrian'	, '(INN) Innsbruck',	'9:45 PM',	'En Route'],
  ['LH 1590', 'Lufthansa'	, '(INN) Innsbruck',	'9:45 PM',	'En Route'],
  ['LH 1082',	'Lufthansa'	, '(LYS) Lyon',	'9:45 PM',	'En Route'],
  ['SQ 2182', 'Singapore Airlines'	, '(LYS) Lyon',	'9:45 PM',	'En Route'],
  ['SK 3339', 'SAS'	, '(LYS) Lyon',	'9:45 PM',	'En Route'],
  ['LO 4733', 'LOT - Polish Airlines'	, '(LYS) Lyon',	'9:45 PM',	'En Route'],
  ['LH 1374',	'Lufthansa'	, '(WRO) Wroclaw',	'9:50 PM',	'En Route'],
  ['LO 5398', 'LOT - Polish Airlines'	, '(WRO) Wroclaw',	'9:50 PM',	'En Route'],
  ['LH 820',	'Lufthansa'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['SK 3690', 'SAS'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['OS 7433', 'Austrian'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['NH 6193', 'ANA'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['SQ 2188', 'Singapore Airlines'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['A3 1430', 'Aegean Airlines'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['TP 7504', 'TAP Portugal'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['SN 7069', 'Brussels Airlines'	, '(GOT) Gothenburg',	'9:50 PM',	'En Route'],
  ['LH 1246',	'Lufthansa'	, '(VIE) Vienna',	'9:50 PM',	'En Route'],
  ['OS 7210', 'Austrian'	, '(VIE) Vienna',	'9:50 PM',	'En Route'],
  ['SK 3729', 'SAS'	, '(VIE) Vienna',	'9:50 PM',	'En Route'],
  ['SQ 2082', 'Singapore Airlines'	, '(VIE) Vienna',	'9:50 PM',	'En Route'],
  ['LH 1410',	'Lufthansa'	, '(BEG) Belgrade',	'9:50 PM',	'En Route'],
  ['UA 9400', 'United Airlines'	, '(BEG) Belgrade',	'9:50 PM',	'En Route'],
  ['SK 3124', 'SAS'	, '(BEG) Belgrade',	'9:50 PM',	'En Route'],
  ['LH 842',	'Lufthansa'	, '(BLL) Billund',	'9:50 PM',	'En Route'],
  ['TP 7568', 'TAP Portugal'	, '(BLL) Billund',	'9:50 PM',	'En Route'],
  ['SQ 2179', 'Singapore Airlines'	, '(BLL) Billund',	'9:50 PM',	'En Route'],
  ['LH 242',	'Lufthansa'	, '(FCO) Rome',	'9:55 PM',	'En Route'],
  ['LH 136',	'Lufthansa'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['TP 7658', 'TAP Portugal'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['TG 7966', 'Thai Airways International'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['SQ 2054', 'Singapore Airlines'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['JP 9786', 'Adria Airways'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['AI 8829', 'Air India'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['CA 6065', 'Air China'	, '(STR) Stuttgart',	'9:55 PM',	'Landed'],
  ['LH 278',	'Lufthansa'	, '(LIN) Milan',	'9:55 PM',	'En Route'],
  ['LH 832',	'Lufthansa'	, '(CPH) Copenhagen',	'9:55 PM',	'En Route'],
  ['SQ 2020', 'Singapore Airlines'	, '(CPH) Copenhagen',	'9:55 PM',	'En Route'],
  ['SK 3616', 'SAS'	, '(CPH) Copenhagen',	'9:55 PM',	'En Route'],
  ['JP 9753', 'Adria Airways'	, '(CPH) Copenhagen',	'9:55 PM',	'En Route'],
  ['AI 8576', 'Air India'	, '(CPH) Copenhagen',	'9:55 PM',	'En Route'],
  ['A3 1404', 'Aegean Airlines'	, '(CPH) Copenhagen',	'9:55 PM',	'En Route'],
  ['LH 778',	'Lufthansa'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['SQ 2007', 'Singapore Airlines'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['SN 7270', 'Brussels Airlines'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['SQ 325',	'Singapore Airlines'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['VA 5678', 'Virgin Australia'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['TP 8417', 'TAP Portugal'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['OU 5810', 'Croatia Airlines'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['NZ 3325', 'Air New Zealand'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['LH 9764', 'Lufthansa'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['JP 9452', 'Adria Airways'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['A3 1204', 'Aegean Airlines'	, '(SIN) Singapore',	'9:55 PM',	'En Route'],
  ['LH 1256',	'Lufthansa'	, '(LNZ) Linz',	'9:55 PM',	'En Route'],
  ['SK 8548', 'SAS'	, '(LNZ) Linz',	'9:55 PM',	'En Route'],
  ['OS 7218', 'Austrian'	, '(LNZ) Linz',	'9:55 PM',	'En Route'],
  ['LH 958',	'Lufthansa'	, '(BHX) Birmingham',	'9:55 PM',	'En Route'],
  ['SQ 2144', 'Singapore Airlines'	, '(BHX) Birmingham',	'9:55 PM',	'En Route'],
  ['LH 772',	'Lufthansa'	, '(BKK) Bangkok',	'10:00 PM',	'En Route'],
  ['LH 572',	'Lufthansa'	, '(JNB) Johannesburg',	'10:00 PM',	'En Route'],
  ['UA 9138', 'United Airlines'	, '(JNB) Johannesburg',	'10:00 PM',	'En Route'],
  ['SN 7206', 'Brussels Airlines'	, '(JNB) Johannesburg',	'10:00 PM',	'En Route'],
  ['SA 7572', 'South African Airways'	, '(JNB) Johannesburg',	'10:00 PM',	'En Route'],
  ['OS 7315', 'Austrian'	, '(JNB) Johannesburg',	'10:00 PM',	'En Route'],
  ['NH 5422', 'ANA'	, '(JNB) Johannesburg',	'10:00 PM',	'En Route'],
];